---
title: "Grandparent Gender and Child Growth"
author: "Bastiaan Quast"
bibliography: bibliography.bib
output:
  html_document:
    number_sections: yes
  pdf_document:
    number_sections: yes
keywords:
- development
- gender
- growth
preamble: |
  \usepackage{amsmath}
abstract: The effect of the gender of a pension recipient on growth of children in
  the same household; an impact evaluation of the lowering of the male pension age
  from 65 to 60.
---

# Introduction

The effect of the gender of a pension recipient on growth of children in the same household; an impact evaluation of the lowering of the male pension age from 65 to 60 in South Africa.


# Methods

Based onDuflo [-@duflo2000child; -@duflo2003grandmothers].
Difference-in-differences, maybe use plm package [@croissant2008panel], maybe world bank.



# Data

The data comes from the National Income Dynamics Survey in South Africa conducted by the Southern Africa Labour and Development Research Unit [-@saldru2008nids; -@saldru2012nids; -@saldru2013nids].

For more information on the data-collection methodology see Leibbrandt et al. [-@leibbrandt2009methodology]

# Results

```{r res}
1+1
```


# Conclusions and Limitations

Not much yet.


# References
\setlength{\parindent}{-0.2in}
\setlength{\leftskip}{0.2in}
\setlength{\parskip}{8pt}